services:
  - type: web
    name: college-event-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromConfig: true
      - key: JWT_SECRET
        generateValue: true
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
